= Solution Pattern: Run your private workloads in Disconnected HCP OpenShift clusters with OpenShift Virtualization
:page-layout: home
:sectnums:
:sectlinks:
:doctype: book

The OpenShift 4 Hosted Control Plane (HCP), often referred to as "HyperShift," is an architectural innovation that allows for the separation of the control plane from the worker nodes in OpenShift clusters. This separation enables the control plane to be hosted independently on a managed infrastructure without the need for dedicated virtual or physical machines, which provides several benefits, especially in terms of scalability, resource efficiency, and management overhead.

This solution pattern presents an architectural solution demonstrating how you can run your private workloads in Disconnected HCP OpenShift clusters using OpenShift Virtualization.


*Contributors:* Gaurav Midha, Juan Manuel Parrilla Madrid

++++
 <br>
++++
[NOTE]
====
Solutions Patterns help you understand the art of the possible with Red Hat's portfolio, and not intended to be used as is for production environments. You are welcome use any part of this solution pattern for your own workloads.
====
[#use-cases]
== Use cases

Common use cases that can be addressed with this architecture are:

- Organizations want to run their private workloads using OpenShift Virtualization. 
- It takes longer than expected to create a cluster.
- Platform teams don't want workload admins/developers to have access to control-planes.
- There is one large server, but it's too much to host just one cluster.
- Organizations need more space for workloads in their cluster.
- It takes a lot of compute to host control planes.
- Organizations face CRD conflicts between tenants.



include::01-pattern.adoc[]
